kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role-binding
  namespace: default
subjects:
  - kind: User
    name: noob # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: pro # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: developer # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io
