kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: duplicated-binding
  namespace: default
  labels:
    refcount: "5"
subjects:
  - kind: User
    name: pro # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-admin # must match the name of the Role
  apiGroup: rbac.authorization.k8s.io
