# permissions for end users to view impliedroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impliedroles-viewer-role
rules:
- apiGroups:
  - role.k8s.com
  resources:
  - impliedroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - role.k8s.com
  resources:
  - impliedroles/status
  verbs:
  - get
