# permissions for end users to edit impliedroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impliedroles-editor-role
rules:
- apiGroups:
  - role.k8s.com
  resources:
  - impliedroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - role.k8s.com
  resources:
  - impliedroles/status
  verbs:
  - get
