
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - role.k8s.com
  resources:
  - impliedroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - role.k8s.com
  resources:
  - impliedroles/finalizers
  verbs:
  - update
- apiGroups:
  - role.k8s.com
  resources:
  - impliedroles/status
  verbs:
  - get
  - patch
  - update
