// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleImplicationRule) DeepCopyInto(out *RoleImplicationRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleImplicationRule.
func (in *RoleImplicationRule) DeepCopy() *RoleImplicationRule {
	if in == nil {
		return nil
	}
	out := new(RoleImplicationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleImplicationRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleImplicationRuleList) DeepCopyInto(out *RoleImplicationRuleList) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleImplicationRuleList.
func (in *RoleImplicationRuleList) DeepCopy() *RoleImplicationRuleList {
	if in == nil {
		return nil
	}
	out := new(RoleImplicationRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoleImplicationRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleImplicationRuleSpec) DeepCopyInto(out *RoleImplicationRuleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleImplicationRuleSpec.
func (in *RoleImplicationRuleSpec) DeepCopy() *RoleImplicationRuleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleImplicationRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleImplicationRuleStatus) DeepCopyInto(out *RoleImplicationRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleImplicationRuleStatus.
func (in *RoleImplicationRuleStatus) DeepCopy() *RoleImplicationRuleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleImplicationRuleStatus)
	in.DeepCopyInto(out)
	return out
}
