
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - role.neu.edu
  resources:
  - roleimplicationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - role.neu.edu
  resources:
  - roleimplicationrules/finalizers
  verbs:
  - update
- apiGroups:
  - role.neu.edu
  resources:
  - roleimplicationrules/status
  verbs:
  - get
  - patch
  - update
