# permissions for end users to view roleimplicationrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roleimplicationrule-viewer-role
rules:
- apiGroups:
  - role.neu.edu
  resources:
  - roleimplicationrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - role.neu.edu
  resources:
  - roleimplicationrules/status
  verbs:
  - get
